config/routes.rb
Rails.application.routes.draw do
  get 'about' => 'about#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'groups#index'
  resources :groups
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:Group, :url, :nameurl)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
	if user_signed_in?
	  redirect_to posts_path
	else
	  redirect_to new_user_session_path
  end
end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="col-md-4 col-md-offset-4"> 
    <div class="form-group">
      <%= form.label :Name %><br/>
      <%= form.text_field :Group, id: :group_Group, class: "form-control", autofocus: true %>
    </div>

    <div class="form-group">
      <%= form.label :url %><br/>
      <%= form.text_field :url, id: :group_url, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :Description %><br/>
      <%= form.text_field :nameurl, id: :group_nameurl, class: "form-control" %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  </div>
</div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<div class="row">
  <div class="col-md-4">
    <p>
      <%= link_to 'Back', groups_path, class: "btn btn-default" %>
    </p>
  </div>
</div>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>
<div class="row">
  <div class="col-md-4">
    <p>
      <%= link_to 'New Post', new_group_path, class: "btn btn-default" %>
    </p>
  </div>
</div>

    <% @groups.each_slice(2) do |slice| %>
    <!-- Example row of columns -->
        <div class="row">
          <% slice.each do |group| %>
          <div class="col-md-6">
            <h2><%= group.Group %></h2>
            <p>
              <% url_embed = "https://www.youtube.com/embed/" + YouTubeAddy.extract_video_id(group.url) %>
              <iframe width="560" height="315" src="<%= url_embed %>" frameborder="0" gesture="media" allow="encrypted-media" allowfullscreen></iframe><br>
            </p>
            <p><%= group.nameurl %> </p>
            <div class="btn-group btn-group-justified" role="group" aria-label="...">
             <div class="btn-group" role="group">
              <%= link_to 'Edit', edit_group_path(group), class: "btn btn-default" %>
             </div>
             <div class="btn-group" role="group">
              <%= link_to 'Delete', group, method: :delete, data: { confirm: 'Are you sure?' }, 
              class: "btn btn-default" %>
             </div>
            </div>
          </div>
          <% end -%>
        </div>
    <% end -%>

<br>

<div class="row">
  <div class="col-md-4">
    <p>
      <%= link_to 'New Post', new_group_path, class: "btn btn-default" %>
    </p>
  </div>
</div>
  

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

<div class="row">
  <div class="col-md-4">
    <p>
      <%= link_to 'Back', groups_path, class: "btn btn-default" %>
    </p>
  </div>
</div>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h2>Name of the post:</h2>
  <h3><%= @group.Group %></h3>
</p>
<p>
  <% url_embed = "https://www.youtube.com/embed/" + YouTubeAddy.extract_video_id(@group.url) %>
  <iframe width="560" height="315" src="<%= url_embed %>" frameborder="0" gesture="media" allow="encrypted-media" allowfullscreen></iframe><br>
</p>
<p>
  <h2>Description:</h2>
  <h5><%= @group.nameurl %></h5>
</p>
  
<div class="row">
  <div class="col-md-4">
    <p>
      <%= link_to 'Back', groups_path, class: "btn btn-default" %>
    </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Links To Laugh</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="icon" href="../../../../favicon.ico">
    <!-- Bootstrap core CSS -->
    <link href="../../../../dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="signin.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="jumbotron.css" rel="stylesheet">
  </head>

  <body>
     <nav class="navbar navbar-inverse">
        <div class="container">
          <ul class="nav navbar-nav">
            <li><%= link_to "Links to laugh", root_path %></li>
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "About", about_path %></li>
            </ul>
          <% if user_signed_in? %>
          <ul class="nav navbar-nav navbar-right">
           <li>
            <%= current_user.name %>
           </li>
           <li>
            <%= link_to "Sign out", destroy_user_session_path, :method => 'delete' %> 
           </li>
          </ul>
          <% end %>
      </div>
    </nav>

    <%= render 'partials/jumbotron' %>

    <main role="main">


      <div class="container">
        <%= yield %>

        <hr>

      </div> <!-- /container -->

    </main>

    <%= render 'partials/footer' %>

  </body>
</html>

app/views/partials/_footer.html.erb
<footer class="container">
      <p>&copy; UnB FGA 2017</p>
</footer>

app/views/partials/_jumbotron.html.erb
<!-- Main jumbotron for a primary marketing message or call to action -->
<% if params[:controller] == 'about' %>
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3">Links to laugh</h1>
          <p>Site produzido pelos alunos Caio César de Almeida Beleza e Rossicler Rodrigues Pires Júnior da UnB FGA
          	 na disciplina de Orientação a Objetos do segundo semestre de 2017</p>
        </div>
      </div>
<% end %>

app/views/users/shared/_links.html.erb
	<%- if controller_name != 'sessions' %>
	<div class="row">
		<div class="col-md-4">
		  <p><%= link_to "Log in", new_session_path(resource_name) %></p>
		</div>
	</div><br />
	<% end -%>

	<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
	<div class="row">
		<div class="col-md-4">
		  <p><%= link_to "Sign up", new_registration_path(resource_name) %></p>
		</div>
	</div><br />
	<% end -%>

	<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
	<div class="row">
		<div class="col-md-8">
		  <p><%= link_to "Forgot your password?", new_password_path(resource_name) %></p>
		</div>
	</div><br />
	<% end -%>

	<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
	<div class="row">
		<div class="col-md-4">
		 <p> <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %></p>
		</div>
	</div><br />
	<% end -%>

	<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
	<div class="row">
		<div class="col-md-4">
		  <p><%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %></p>
		</div>
	</div><br />
	<% end -%>

	<%- if devise_mapping.omniauthable? %>
	  <%- resource_class.omniauth_providers.each do |provider| %>
	    <div class="row">
		  <div class="col-md-4">
		    <p><%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %></p>
		  </div>
		</div><br />
	  <% end -%>
	<% end -%>
</div>